language: python
env:
  global:
  - AWS_DEFAULT_REGION=us-west-2

before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin

python:
  -"3.6"

install:
  - pip install -r requirements/production.txt

script:
  - pytest